### ISSUE TITLE
Testarchitektur für das Modul Terminvereinbarung

### ISSUE THREAD

**Issue by alexzautke** [gematik/spec-ISiK-Terminplanung#1]
Als Entwickler vom Titus-Testsystem möchte ich wissen, wie die Testarchitektur für das Modul Terminvereinbarung aussehen könnte, um zu entscheiden, welche Funktionalitäten für das Titus-System entwickelt werden müssen.

AC:

- [ ] Die möglichen Architekturen wurden skizziert.

- [ ] Die dazugehörigen Sequenzdiagramme wurden skizziert.

**Comment by f-peverali** [comment]
Analog zu https://github.com/gematik/spec-ISiK-Medikation/issues/1

**Comment by f-peverali** [comment]
Test-System ist aufgesetzt und Produkt und Ticket damit obsolet.
