### ISSUE TITLE
Extension "ISiKKalenderNameExtension" durch Empfehlung der Deutschen Basisprofile ersetzen

### ISSUE THREAD

**Issue by alexzautke** [gematik/spec-ISiK-Terminplanung#53]
Anstatt der Extension ISiKKalenderNameExtension sollte eine Backport-Extension aus FHIR R5 verwendet werden. Siehe Empfehlung der Deutschen Basisprofile: https://github.com/hl7germany/basisprofil-de-r4/pull/493

**Comment by f-peverali** [comment]
Bin mir hier unsicher. Wo kann ich diese Extension finden, @alexzautke ? 

Folgendermaßen in fsh? 

* extension MS
* extension contains http://hl7.org/fhir/5.0/StructureDefinition/extension-Schedule.name named KalenderName 0..1 MS

Muss ich noch auf dependencies achten?

**Comment by alexzautke** [comment]
Die Backport-Extensions sind „virtuell“, d.h. es gibt kein Package mit einer StructureDefinition dafür. Dies muss entsprechend erstellt werden und im ISiK-Projekt hochgeladen werden. Es gibt schon eine andere Backport-Extension im Projekt wo man sich das Muster ansehen kann.

Das FSH-Snippet sieht korrekt aus.

**Comment by f-peverali** [comment]
Zu prüfen, ob in TC umsetzbar.

**Comment by f-peverali** [comment]
> Backport-Extensions sind „virtuell“, d.h. es gibt kein Package mit einer StructureDefinition dafür. Dies muss entsprechend erstellt werden und im ISiK-Projekt hochgeladen werden

Mir ist weiterhin Unklar, wie die extension aussehen soll. ID und Benennung (z.B. "ScheduleName") sollten auch mit einer zukünftigen R5 extension übereinstimmen. Oder liege ich falsch?

**Comment by f-peverali** [comment]
Hier ein Vorschlag: https://github.com/gematik/spec-ISiK-Terminplanung/pull/61

**Comment by f-peverali** [comment]
@patrickwladowska hierfür ggf. test hinzu
