### ISSUE TITLE
ISiKTerminKontaktMitGesundheitseinrichtung ist im IG nicht unter Datenobjekte aufgeführt (Kommentierung Stufe 3)

### ISSUE THREAD

**Issue by alexzautke** [gematik/spec-ISiK-Terminplanung#60]
Im IG wurde eine Unterseite vergessen. Diese sollte entsprechend dem Template der anderen Seiten unter Datenobjekte hinzugefügt werden.

**Comment by f-peverali** [comment]
Das sieht mir nach einem Problem in der Runtime von Sinplifier aus:

bei einigen Aufrufen wird diese Seite (https://simplifier.net/guide/isik-terminplanung/ImplementationGuide-markdown-Datenobjekte-ISiKKalenderSchedule?version=current) korrekt gerendert.
Dann erhalte ich für die gleiche Seite wiederum:
Command 'page-with-children' could not render: Response did not arrive on time in 00:00:30 for message: Request *cli/a7503f85@92659b9e->S10.240.0.59:30000:0*grn/Clovis.Grains.Fql.FqlGrain/0 InvokeMethodRequest Clovis.Interfaces.IFqlGrain:Execute #42330. Target History is: .

Oder kann ich hier noch etwas in Sachen FQL im Editor ändern?

**Comment by alexzautke** [comment]
Simplifier hat gerade akute DDoS Probleme... Das Team ist bereits dabei das Problem zu beheben

**Comment by f-peverali** [comment]
Hoffe nicht zu schlimm. Ich schließe das Ticket aber, da der Fehler höchstwahrscheinlich nicht im Code liegt.

**Comment by alexzautke** [comment]
Die Seite im IG fehlt aber trotzdem...

**Comment by alexzautke** [comment]
Wir brauchen eine neue Seite für das Encounter-Profil

**Comment by f-peverali** [comment]
HI Frage: alle Termine sind aufgrund der Vererbung "Abteilungskontakte"... ist das gewollt oder ein Problem?

**Comment by alexzautke** [comment]
Oh! Das ist ein Problem.

**Comment by f-peverali** [comment]
Dann wäre mein Vorgehen: Wir kennzeichnen das für Stufe 2 im IG als zu lösendes Problem mit anstehenden TC Release.
Für Stufe 3 würde ich dann dagegen eine generischen Encounter nachbauen, der diese Restriction (Pattern) nicht mitführt (und ggf. weitere Modifikation im Sinne einer (umfassenden und flexiblen) Terminplanung ermöglicht). 

Gegenvorschläge zum Vorgehen? FYI @JoshuaBolte

**Comment by alexzautke** [comment]
Das bedeutet auch, dass in Stufe 2 kaum verwendet werden kann. Am Besten sollte es bereits dort gelöst werden. Der Encounter in dieser Form macht kaum Sinn.

**Comment by f-peverali** [comment]
Wird erst mit TC im Februar erfolgen, da größeres Thema

**Comment by f-peverali** [comment]
Mit Ansgar besprochen-optionen:
- Absprache mit AG (abklopfen auf Relevanz der Kodierung)
- ggf. mit Bvitg
- Vor Entscheidung Abstimmung mit Industrie

**Comment by f-peverali** [comment]
> Hier eine Frage: alle Termine sind aufgrund der Vererbung "Abteilungskontakte"... ist das gewollt oder ein Problem?

Lösung: pattern raus (ggf. noch constraint spezifizieren für verschiedene Referenzierungsfälle)

**Comment by jcaumann** [comment]
Zu der Frage, ob die Einschränkung auf den "Abteilungskontakt" gewollt oder ein Problem ist, werfe ich mal als dritte Option "beides" ins Rennen. Im einleitenden Text zu der IG steht der Satz "Encounter im ISiK-Kontext sind stets als "Abteilungskontakte, im Sinne der MI-I mit dem entsprechenden Encounter.type-Code, zu kennzeichnen.". D.h. das ist hier durchaus so gewollt und wird im IG weiter oben aus Anforderungen aus der Kontaktnachverfolgung von Infektionsketten motiviert (wozu ich aber leider auf der referenzierten Seite aus der MII nichts finden konnte). Wenn das der einzige Grund ist, finde ich eine Kardinalität von "1..*" nicht angemessen, da das dann doch ein sehr spezifischer UseCase ist, den man nicht fest an eine so generische Ressource wie Encounter binden sollte.

**Comment by f-peverali** [comment]
Lösungsweg abgestimmt mit @jcaumann 
- Profil ISiKTerminKontaktMitGesundheitseinrichtung (ENcounter) kann aus dem Modul Terminplanung entfernt werden (als TC)
- ggf. Hinweis zur Verknüpfung mit Terminplanung im IG der Basisstufe 2

**Comment by alexzautke** [comment]
@f-peverali Wie gehst du dann mit dem MS-Flag auf .appointment um, in dem Fall dass das Profil entfernt wird?

**Comment by f-peverali** [comment]
@alexzautke annahme war, dass enounter selbst keine notwendige Ressource für die Terminbuchung darstellt.
Wer in einem Encounter (rückwirkend) ein Appointment referenzieren will, kann das, sollte aber nicht dazu gezwungen werden. 
Oder besteht hier eine Notwednigkeit, die ich nicht sehe?

ggf. hätte ich mit dem hinweis in Encoutnter Basis 2 auf die Möglichkeit der Verknüpfung verwiesen.

**Comment by alexzautke** [comment]
Die Notwendigkeit ist, dass jedes System, dass ein Termin entgegen nimmt auch in der Lage sein sollte den Termin im Encounter zu exponieren. Das geht nur über das MS-Flag.

**Comment by alexzautke** [comment]
Ansonsten hat der Appointment Consumer das Problem, dass man nicht mehr weiß an welchen Encounter alle weiteren Informationen gehangen wurden / werden.

**Comment by jcaumann** [comment]
Aus meiner Sicht haben wir bei der Bindung eines Appointment an einen Encounter kein Interoperabilitätsproblem, da das systemintern erfolgt - sofern diese Bindung überhaupt erforderlich ist. 
Wenn der Patient oder der den Termin für den Patienten buchende Arzt weitere Informationen mitgeben möchte, dann werden diese über geeignete Verfahren (KIM, ePA, etc.) an den "gebuchten" Arzt übermittelt. Dieser entscheidet, ob diese Informationen für die Behandlung relevant sind  und bindet sie dann ggf. im Kontext des Besuchs an den Encounter.
Dieser strikte Bruch im Ablauf ist auch daher wichtig, weil die Vermittlung von Appointments zu Slots auch eine durch einen Dritten realisierte Leistung sein kann (siehe zB doctolib im ambulanten Bereich). Dieser übergibt das Appointment an seinen "Auftraggeber" (dh den Besitzer des zugrundeliegenden Kalenders) und wird niemals etwas von einem ggf. aus dem Appointment erwachsenden Encounter mitbekommen (dürfen!). Die in FHIR vorgesehene Rückwärtsverlinkung von einem Encounter zu einem Appointment ist nach meinem Verständnis vor allem dann relevant, wenn der konkrete Workflow der Terminvermittlung Auswirkungen auf die Abrechnung hat (z.B. TSVG-Zuschläge bei kurzfristiger Vermittlung durch eine TSS im ambulanten Bereich). In jedem Fall bleibt das Appointment aber ein rein administratives Objekt, auf dem weiter administrative Abläufe laufen können (zB Terminabsagen). Das erfolgt aber vollkommen lösgelöst von dem medizinischen Geschehen rund um den Encounter.

**Comment by f-peverali** [comment]
Absprache mit Alexander notwendig...

**Comment by f-peverali** [comment]
hier ein Hinweis zur Entscheidung : https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BTerminplanung.5D.20-.20ISiKKontaktGesundheitseinrichtung/near/286061961 FYI @jcaumann

**Comment by patrick-werner** [comment]
Es geht hier um das KIS, welches Schnittstellen zur Verfügung steht um Terminbuchungen/Reservierungen durchführen zu können.
Daher ist es nur sinnvoll, wenn das Appointment mit dem Encounter verknüpft wird. Ja externe Auftraggeber werden dies meist nicht mitbekommen, aber für die Datensicht innerhalb eine Krankenhauses ist sinnvoll zu wissen aus welchen Appointments welche Encounter entstanden sind.

**Comment by jcaumann** [comment]
Das sollte aber auch ohne Encounter im "Block" der Termin-Profile funktionieren. In dem skizzierten Szenario würde das KIS Schnittstellen - z.B. für ein Zuweiserprotal - zur Verfügung stellen, über die Termine gebucht werden können. Am Ende resultiert das in einem Appointment im Kalender des KIS. Der Encounter als medizinisches Pendant wird ebenfalls im KIS angelegt (so meine These). Das KIS kann dann Encounter und Appointment verknüpfen. Das ist dann aber KIS-intern und kein Thema für eine Interoperabilitätsfestlegung. 
Als wichtig für Interoeprabilität würde ich vorrangig die Schnittstelle des KIS zur Terminbuchung sehen (Schedule, Slot, Appointment) und die Schnittstelle zum Abruf des Encounters, da darüber dann Daten abgefragt werden können und auch die Berechtigungen bei Smart-on-FHIR an den Encounter gehängt werden können. Die Verknüpfung Encounter-Appointment wäre in meinem Bild dann nur KIS-intern relevant und müsste nicht zwingend exponiert werden.

**Comment by f-peverali** [comment]
@jcaumann FYI

**Comment by jcaumann** [comment]
@mwedekind-dev: Wenn im Kontext des Encounters ein Austausch von Dokumenten erforderlich ist, dann impliziere ich einmal, dass es sich dann dabei um medizinische Daten handelt, zB einen Vorbefund, eine Bescheinigung, einen Befundbericht, etc. Um dieses zwischen Arzt und Patient auszutauschen, soll die ePA genutzt werden, die durch das kommende Opt-Out dann auch nutzbar wird und die einen sicheren Austausch garantiert. Die Nutzung herstellerspezifischer Datenaustauschplattformen ist durch die Spezifikation nicht ausgeschlossen, stellt aber aus meiner Sicht - z.B. im Gegensatz zu ePA, TIM und KIM - keinen UseCase dar, der in besonderem Maße mit ISiK unterstützen werden muss. Dies umso mehr, wenn dadurch für Häuser, die die für den sicheren Dokumentenaustausch mit Patienten vorgesehenen Anwendungen der TI nutzen, Implementierungsmehraufwände entstehen, die für die Nutzung von ePA&Co. nicht erforderlich sind.

**Comment by f-peverali** [comment]
In dem Sinne würde ich für die Kommentierung der Stufe 3 den spezifischen Encounter aus dem Modul Terminplanung entfernen

**Comment by pavlodyban** [comment]
Das Profil ISiKTerminKontaktMitGesundheitseinrichtung stellt den Link zwischen dem Encounter und dem Appointment her und ist für die Umsetzung der ISiK v2 Terminplanung Spec sowie der ISiK v3 Dokumentenaustausch Spec absolut notwendig.

*"Das KIS kann dann Encounter und Appointment verknüpfen. Das ist dann aber KIS-intern und kein Thema für eine Interoperabilitätsfestlegung."*
Die Verbindung des Termins zum Encounter ist trotz der oberen Annahme nicht systemintern, sondern muss an die Portale (Zuweiser- oder Patientenportale) exponiert werden.

Der beispielhafte Usecase ergibt sich aus den KHZG-Anforderungen: Patienten und Zuweiser sollen die Möglichkeit haben, Dokumente über die Portale im Sinne des FTB2 an das KIS zu senden. Das Portal arbeitet in erster Linie nur mit Terminen, aber das KIS kann Dokumente nur mit Fallbezug (und nicht Terminbezug) entgegennehmen. Die Verlinkung Termin zum Fall muss unbedingt exponiert werden, damit die Portale den Fallbezug aus dem Termin ermitteln und Dokumente ans KIS senden können. 

Die Annahme, dass Dokumente nur über die ePA gesendet würden, entspricht nicht der Realität. Die Portale haben i.d.R. keinen Anschluss an die TI und dürfen kein Frontend des Versicherten abbilden. Dokumente, die keinen medizinischen Wert haben (Wahlleistungsvereinbarungen, Verträge, Orientierungshilfen etc.), haben gar nichts in der ePA zu suchen. Außerdem müssen besonders im stationären Kontext Dokumente (z.B. Scmerzskala) von Patienten direkt aus dem Portal ins KIS geschickt werden können. Zuletzt muss diese Funktion auch für die Benutzer dastehen, die der ePA-Nutzung widersprechen, aber das Portal für ihren Krankenhausaufenthalt benutzen.

Man kann natürlich die Anwender zwingen den Fallkontext manuell im Patientenportal herzustellen (bevor Dokumente ans KIS exportiert werden können), aber das erhöht den Aufwand, birgt die Gefahr der Falschzuordnung und widerspricht dem eigentlichen Ziel der Interoperabilität.

**Aus all diesen Gründen müssen das Profil ISiKKontaktGesundheitseinrichtung und das Must-Support-Flag für das Appointment Element erhalten bleiben.**

**Comment by f-peverali** [comment]
Das Profil sollte wieder in das Modul eingehen und aus den oben genannten Erläuterungen eine IG-Seite erstellt werden.

**Comment by f-peverali** [comment]
> Die Verlinkung Termin zum Fall muss unbedingt exponiert werden, damit [1] die Portale den Fallbezug aus dem Termin ermitteln und [2] Dokumente ans KIS senden können.

Gibt es hier die Notwendigkeit weitere REST-Operations für die genannten Use Cases zu definieren?  Könnten andernfalls Hinweise auf in anderen Modulen (z.B. aus Encounter der Basis) definierte Operationen sinnvoll sein? 

Für Fall [2] wäre es womöglich sinnvoll einen Bezug zu den Interkationen im Modul [Dokumentenaustausch](https://simplifier.net/guide/Implementierungsleitfaden%20ISiK-Modul%20Dokumentenaustausch/ImplementationGuide-markdown-AkteureUndInteraktionen?version=current) im IG des ISiK-Terminplanungs-Moduls herzustellen. Hier sollten keine weiteren Vorgaben zum Dokumentenaustausch (zu Operations) getroffen werden.

-> Antworten in der Kommentierungs-AG : zu 1) nein zu 2) ja, sinnvoll

**Comment by f-peverali** [comment]
Die Encounter-Beschreibung wurde hiermit erstellt: https://github.com/gematik/spec-ISiK-Terminplanung/pull/90/commits/99d2cfe315b58e5b628c293817eb04c846ecd416
