### ISSUE TITLE
Appointment.specialty auf 0..1 MS statt 1..1 (Kommentierung Stufe 3)

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Terminplanung#72]
Hintergrund hier: 
- Meldung von Performance-Problemen bei Implementierung
- Notwendigkeit der Angabe einer Fachrichtung für ein Appointment (bei Terminvereinbarung) ist nicht ersichtlich

----
@jcaumann hier übertrage ich nochmal deinen Input:

Beispiel: 

Ein kleineres Krankenhaus bietet in einer Abteilung verschiedene Leistungen für Kinder an. Über ein Zuweiserportal sollen durch Kinderärzte sowohl Termine für bestimmte Untersuchungen als auch für bestimmte chirurgische Eingriffe gebucht werden können. Hierzu wird ein "schedule" angelegt. Die darin vermerkten "speciality" sind 304 (Kinderchirurgie) und 341 (Kinder- und Jugendmedizin). Als "serviceType" sind die angebotenen Leistungen eingetragen, die im Zuweiserporztal als Auswahlliste für die Terminsuche erscheinen.

Umsetzungsoption 1: In dem Kalender werden sowohl "slots" für chirurgische Eingriffe als auch für die angebotenen Untersuchungen eingetragen. Da hier jeweils andere Ressourcen (Räume, Personal, etc.) dran hängen, hat jeder "slot" immer genau eine "speciality" und als "serviceType" die in diesem "slot" angebotenen Leistungen. Der Kinderarzt wählt im Zuweiserprotal über die im "schedule" aufgelisteten "serviceType" aus, welche Leistung er für seinen Patienten buchen möchte. Anschließend werden die verfügbaren "slot" gesucht, die als "serviceType" die gesuchte Leistung besitzen. Der Kinderarzt wählt einen Termin aus und bucht diesen. Damit wird ein "appointment" angelegt. In diesen werden die "speciality" aus dem "slot" und der ausgewählte "serviceType" übernommen. 

Fazit: Wenn Übernahme der "speciality", dann besser aus dem "slot" und nicht aus dem "schedule". Aber: In diesem Beispiel wird die "speciality" überhaupt nicht benötigt und könnte auch weggelassen werden.

Umsetzungsoption 2: Da chirurgische Eingriffe eher selten angefragt werden, werden alle "slots" des "schedule" ohne spezifische Zuordnung von "speciality" und "serviceType" angelegt. Analog zu Umsetzung 1 kann der Kinderarzt im Portal aus den "serviceType" wählen und bekommt eine Liste der freien Slots, aus denen er einen auswählt. Wenn er eine Untersuchung wählt, wird direkt das Appointment mit der "speciality" 341 und dem gewählten "serviceType" angelegt und der Termin gegenüber dem Kinderarzt bestätigt. Wenn ein chirurgischer Termin angefragt ist, erhält der Arzt nur eine Reservierungsbestätigung. Die Anfrage landet im Krankenhaus bei einen Disponenten, der prüft, ob der Termin einrichtbar ist. Erst dann wird das "appointment" angelegt und der einweisende Kinderarzt erhält eine Terminbestätigung (oder einen alternativen Terminvorschlag). Auch hier hat das "appointment" nur eine "speciality" (304) und einen "serviceType".

Fazit: Hier wäre die "speciality" in "schedule" und "slot" noch unwichtiger als in der ersten Umsetzung, da das Setzen der  "speciality" im "appointment" nur anhand des gewählten "serviceType" erfolgt und eigentlich nur erforderlich ist, wenn der automatische Workflow weiterläuft und z. B. irgendwelche Ressourcenplanungen aus der "speciality" des "appointment" abgeleitet werden.

Gesamtfazit: Wenn das ein typischer UseCases ist, dann wäre bei "speciality" durchgängig eigentlich "0..*" passender und das "MS" wäre eher fraglich. Auch braucht man dann eine Abfrage nach "serviceType" auf "slot", die aktuell nicht vorgeschrieben ist.

**Comment by pavlodyban** [comment]
*"FHIR erlaubt die Anlage von Appointments ohne Bindung an einen Slot und außerhalb des Worksflows über einen Kalender. Dies kann z.B. auch dann erforderlich sein, wenn ein Termin außerhalb der definierten Slots per Telefon vereinbart und dann in das System eingespeist wird. In diesem Fall findet keine "Vererbung" von serviceType und specialty aus einem Kalender statt."*

Die Aussage oben (aus dem Changelog, welches aus diesem Issue hervorging) stimmt leider nicht mit der Praxis überein. Telefonische Termine werden ebenfalls mit einem Bezug zu einer Leistung und zu einer Ressource angelegt. Ein Termin ohne Bezug zur Ressource oder einer Leistung kann nicht sinnvoll für Prozesssteuerung benutzt werden.

Damit muss die Kardinalität von Appointment.serviceType auf 1..1 bleiben.

**Comment by f-peverali** [comment]
Wie in der Diskussionsrunde vom 19.4.2023 angeregt, soll die Änderung von Appointment.serviceType rückgängig gemacht werden und ebenso ist zu diskutieren, ob für Appointment.specialty der Status Quo von Stufe 2 erhalten bleiben soll. Die Argumentation weist auf einen UC hin, für den gilt: Patienten benötigen in der Darstellung eines Termins die Informationen aus besagten Elementen. Generell seien die Informationen für die Prozesssteuerung in der Terminbuchung notwendig.

FYI @jcaumann

**Comment by hhec** [comment]
Zu der Appointment.specialty folgende Gedanken, die in die Diskussion einfließen sollten:

Grundlegend sollte das Prinzip verfolgt werden, dass Wissen über das Regelwerk einer Terminbuchung in genau einem System liegt. Da Terminbuchungen normalerweise sowohl KIS intern, wie nun bald durch ISiK als default auch von Portalen durchgeführt werden sollen, wäre trotzdem davon auszugehen, dass das "vorhandene" Regelwerk im KIS nicht obsolet wird. 
=> Also kann man die Arbeitshypothese aufstellen, dass das KIS das Wissen über die Termibuchungsregeln hat. 
=> Das impliziert, dass der Client kein Wissen über Terminbuchungsregeln haben soll/darf!

1. In der Spec ist weder Slot.specialty noch Schedule.specialty eine Pflichtangabe. Entsprechend ist es fragwürdig, dass bei Appointment dies dann Pflicht sein soll, wenn man der obigen Arbeitshypothese folgt und der Client kein Wissen über Terminbuchungsregeln halten soll! Es kann durchaus überlegt werden im IG anzugeben, dass wenn Slot und/oder Schedule die Specialty zurückgibt, dass es dann für diese Buchung im Appointment.specialty zwingend wieder "zurückgespiegelt" werden soll. 
2. Es gibt Systeme, die nicht zwingend auf dieser Information Terminbuchungsregeln anwenden. Es wäre also forsch dies für alle Pflicht zu machen, nur weil es Systeme gibt, die dies tun.

**Comment by pavlodyban** [comment]
*"Das impliziert, dass der Client kein Wissen über Terminbuchungsregeln haben soll/darf!"*
Die Schlussfolgerung oben stimmt nur bedingt. Es ist durchaus verbreitert, dass das KIS das Regelwerk für die interne Terminbuchung behält, wobei das davor geschaltetes Patientenportal das eigene Regelwerk für die Online-Termine behält. Diese Regelwerke werden zum Teil synchronisiert, damit sie auf den gleichen Kalendern arbeiten, aber die Wahl der Slots steht den beiden Systemen nach ihren jeweiligen Regelwerken zu.
Das Patientenportal fragt nicht im KIS nach einem Slot an, sondern definiert den passenden Slot nach dem eigenen Regelwerk selbst und informiert das KIS über die neue Terminbuchung mit Bezug auf den Schedule (`$book` mit `Appointment` und `Schedule` als Parameter).
Der geschilderte Usecase existiert parallel zum Fall, wo nur das KIS das Regelwerk kennt und das Portal das KIS nach verfügbaren Slots fragt. Beide Szenarien der Terminbuchung sind mit ISiK v2 möglich.

`Schedule.specialty` hat in der Spec (v2 und v3) die Kardinalität `1..1`, und das ist aus meiner Sicht richtig so. Ein Kalender existiert nicht ohne eine Fachrichtung / Organisationseinheit im KIS. 

@hhec Könnten Sie einen Usecase schildern, bei dem in Ihrem System die Kalender die Zuordnung zur OE oder Fachrichtung nicht erhalten?

**Comment by hhec** [comment]
Bitte entschuldigen Sie, mir ist der Fehler unterlaufen, dass Schedule.specialty mit 1..1 angegeben ist!

Meine Anfrage würde ich weiterhin stellen insofern, dass ich nicht behaupte dass ein Kalender keine Zuordnung zur OE oder Fachrichtung erhalten hat, sondern 
- mehrere (wäre dann zumindest im Schedule eine 1..* Kardinalität und nur über Slot zu konkretisieren auf den angefragten Zeitpunkt) und 
- ggf. OEs ohne eine Zuordnung zum ValueSet [de.basisprofil.r4 | IHEXDSauthorSpeciality - SIMPLIFIER.NET](https://simplifier.net/packages/de.basisprofil.r4/1.4.0/files/656616). 

@pavlodyban was ist denn der Vorteil der Kardinalität 1..1? 
Sie führten an, dass manche Systeme ohne die explizite Angabe der specialty bei der Buchung nicht genau wissen, was damit anzufangen ist.
Wenn es das aus Ihrem Kommentar erwähnte Szenario ist, dass das KIS für diese Slots gar kein eigenes Regelwerk hat sondern das Patientenportal, sollte es nicht relevant sein. Und sollte es nicht das Szenario sein, dann würde es weniger strikt und genauso effektiv über eine Regelung gehandhabt werden können, dass bei Abfrage von Schedule/Slot mit specialty in der Response, dies auch bei der Buchung anzugeben wäre. Hierbei mit dem Vorteil das von mir erwähnte Problem nicht zu haben.

**Comment by pavlodyban** [comment]
Zu Ihren beiden Bulletpoints:
1. Ein `Schedule` stellt einen buchbaren Kalender dar. Ich habe bisher in der Praxis nur Kalender erlebt, die einer Fachrichtung zugeordnet sind und nicht mehreren. Dass ein Behandler oder eine Ressource zur gleichen Zeit in verschiedenen Fachabteilungen genutzt werden und das mit dem selben Kalender abgebildet wird, ist mir noch nicht begegnet. Heißt aber natürlich nicht, dass es das nicht gibt. Wenn ein Primärsystem dieses Verhalten unterstützt, dann soll ISiK diese Funktion freilich nicht einschränken. Dieser Logik folgend, dürfen die Slots nicht die Unterscheidung auf die einzelnen Fachrichtungen innerhalb des Schedules vornehmen. Das explodiert die Business Logik. Hier würde ich mir einen Austausch mit mehreren Primärsystemherstellern und Patportalen wünschen, um für uns alle ein Bild zu bekommen wie häufig das geschilderte Szenario vorkommt.
2. Sehr oft werden die Kalender mehreren OEs zugeordnet (die m.E. alle derselben medizinischen Fachrichtung gehören - TBD). OEs anstelle von XDS Fachrichtungen zu exponieren wäre aus meiner Sicht nicht zielführend, da das abhängige System dann immer noch das Mapping von OEs auf die Fachrichtungen vornehmen müsste. Hier ist für mich die Frage, welches System die Kernkompetenz haben soll, um die OEs auf die medizinischen Fachrichtungen zu mappen. Aus meiner Sicht soll das im KIS passieren und somit sollen erst die XDS Fachrichtungen über ISiK exponiert werden.

Freue mich auf die Diskussion nachher im Call.

**Comment by f-peverali** [comment]
Für specialty wird 0..1 MS gesetzt mit einem Hinweis, der sinngemäß fordert: MUSS exponiert werden, insbesondere für das Rendering gegenüber (Usern) in einem Zuweiserportal/Patienteportal (allgemein GUI).

**Comment by alexzautke** [comment]
@pavlodyban: ```Dass ein Behandler oder eine Ressource zur gleichen Zeit in verschiedenen Fachabteilungen genutzt werden und das mit dem selben Kalender abgebildet wird, ist mir noch nicht begegnet.```

Genau aus diesem Grund hängt in FHIR auch der .actor am Schedule und nicht am Slot! Dort habe ich Verknüpfung zur Location, HealthcareService und weiteren Akteuren. ```Appointment.slot``` daher bei der textuellen Beschreibung zuerst zu nennen halte ich für irreführend.
