### ISSUE TITLE
Buchungsprozess "pending" (Stufe 3?)

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Terminplanung#73]
Buchungsprozess - eine Änderung möglich, sodass der Status „pending“ vom KIS gesetzt wird im Falle eines konfigurierten manuellen Bestätigungsprozesses?
----
 Hintergrund:

- Wissen über Regeln von Terminbuchungen sollte nur in einem System vorgehalten - Single Point of Truth - (beim Primärsystem - nicht beim CLient)
- Stand jetzt: Im Falle des Anwendungsszenarios "Manueller Buchungsprozess" muss Client-seitig Wissen vorhanden sein, um derzeitige asynchronous-$book operation ausführen zu können → hier Problem
- Auch mit Custom Operation ggf. 

Auch hier dein Hinweis @jcaumann :

SIehe Umsetzungsoption-2 aus https://github.com/gematik/spec-ISiK-Terminplanung/issues/72. Hier würde die Reservierung ein "appointment" mit status "pending" herausgegeben und erst nach der manuellen Freigabe der Reservierung der Status auf "booked" geändert. Somit finde ich den Vorschlag  gut, da das gerade für Patienten- und Zuweiserportale als Clients dann deutlich einfacher umsetzbar ist als die asynchrone "$book"-Operation.

**Comment by f-peverali** [comment]
fyi @jcaumann

**Comment by mwedekind-dev** [comment]
@f-peverali : Welches Wissen, das im Client vorhanden sein muss, ist hier genau gemeint?

**Comment by mwedekind-dev** [comment]
Mich irritiert die Formulierung:

> Hier würde die Reservierung ein "appointment" mit status "pending" herausgegeben

Da ich sie so lese, dass der Termin-Server, bspw. das KIS, eine Appointment Ressource herausgibt. Unter herausgeben kann auch "anlegen beim Client" verstanden werden, also bei der Partei, die eigentlich einen Termin im KIS anlegen möchte. Ist hier gemeint: "Hier würde im Terminrepository ein Appointment mit Status "pending" angelegt..."?

**Comment by mwedekind-dev** [comment]
Mich irritiert die Formulierung:

> Hier würde die Reservierung ein "appointment" mit status "pending" herausgegeben

Da ich sie so lese, dass der Termin-Server, bspw. das KIS, eine Appointment Ressource herausgibt. Unter herausgeben kann auch "anlegen beim Client" verstanden werden, also bei der Partei, die eigentlich einen Termin im KIS anlegen möchte. Ist hier gemeint: "Hier würde im Terminrepository ein Appointment mit Status "pending" angelegt..."?

**Comment by mwedekind-dev** [comment]
Mich irritiert die Formulierung:

> Hier würde die Reservierung ein "appointment" mit status "pending" herausgegeben

Da ich sie so lese, dass der Termin-Server, bspw. das KIS, eine Appointment Ressource herausgibt. Unter herausgeben kann auch "anlegen beim Client" verstanden werden, also bei der Partei, die eigentlich einen Termin im KIS anlegen möchte. Ist hier gemeint: "Hier würde im Terminrepository ein Appointment mit Status "pending" angelegt..."?

**Comment by mwedekind-dev** [comment]
Mich irritiert die Formulierung:

> Hier würde die Reservierung ein "appointment" mit status "pending" herausgegeben

Da ich sie so lese, dass der Termin-Server, bspw. das KIS, eine Appointment Ressource herausgibt. Unter herausgeben kann auch "anlegen beim Client" verstanden werden, also bei der Partei, die eigentlich einen Termin im KIS anlegen möchte. Ist hier gemeint: "Hier würde im Terminrepository ein Appointment mit Status "pending" angelegt..."?

**Comment by jcaumann** [comment]
@mwedekind-dev : genau. Es ist gemeint, dass die Ressource mit dem Status "pending" im Repository angelegt wird. Die gewählte Formulierung war hier sehr ungeschickt.
Die Frage die sich dabei stellt ist, ob wir dann nicht auch den http-Status 202 als Rückgabe verlangen, so dass der Client auch auf dem Wege informiert ist, dass er da später noch einmal nachfassen muss.
FYI: @f-peverali

**Comment by f-peverali** [comment]
"Alle Statuswerte MÜSSEN durch ein bestätigungsrelevantes System unterstüzt werden, insbesondere der Status "proposed" und "booked"." (https://simplifier.net/guide/isik-terminplanung/ImplementationGuide-markdown-Datenobjekte-ISiKTerminAppointment?version=current) -> damit muss nach Spec bereits jetzt Status "pending" unterstützt werden, dies wird lediglich momentan nicht in TITUS getestet. FYI @jcaumann
